### PR TITLE
fix: Correct `reporter` usage + set correct peerDep, engines

### PR DESCRIPTION
**Pull request by LekoArts**
Hello, Gatsby maintainer here 👋 

While looking at the plugin I noticed that the `peerDependency` is set incorrectly. It should be a dependency on `gatsby` and not `gatsby-cli`. We're in the process of providing more helpful information on the `/plugins` page of our website and for that we need plugins to set their `peerDependencies` correctly/more specific.

I've also updated the minimum Node version as v3 requires at least 12.13.0.

Thanks!

Fixes https://github.com/algolia/gatsby-plugin-algolia/issues/123
Fixes https://github.com/algolia/gatsby-plugin-algolia/issues/126
Fixes https://github.com/algolia/gatsby-plugin-algolia/issues/97

### CODE REVIEW

**Comment by Haroenv** [comment]
Thanks @LekoArts! I noticed in https://github.com/algolia/gatsby-plugin-algolia/issues/123 that the import for the reporter:

https://github.com/algolia/gatsby-plugin-algolia/blob/c909df74c3a41849dd4f0305e52205386c8b089a/gatsby-node.js#L3

possibly might not work with v3. Do you have any ideas on why that could be?

**Comment by Haroenv** [comment]
Does Gatsby think it's interesting to move this repo to the Gatsby monorepo instead of this repo?

**Comment by LekoArts** [comment]
Hi!

Yeah, the reporter shouldn't be required from `gatsby-cli` but used like here: https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#reporter

It gets added to the APIs:

```js
exports.onPostBuild = ({ reporter }) => {
  reporter.info(`Your Gatsby site has been built!`)
}
```

Generally speaking we currently don't want to add new packages to our monorepo, we only maintain critical plugins and let companies maintain their own ones :)

**Comment by LekoArts** [comment]
https://github.com/algolia/gatsby-plugin-algolia/issues/97 proposes the same (correct) thing :)

**Comment by Haroenv** [comment]
Ah I was confused with it all Lennart, thanks for updating the PR with the fix!

**Comment by LekoArts** [comment]
This code is untested so far, would appreciate if you can give it a test spin (I don't have any algolia set up) :)

**Comment by LekoArts** [comment]
Thanks for the quick merge! As I said, please test it before publishing it 👍

**Comment by Haroenv** [comment]
I had to update the example to v2, but once that was done it all worked, thanks @LekoArts

**Comment by LekoArts** [comment]
Ideally you should upgrade to v3 😅

**Comment by Haroenv** [comment]
yes, I'll do it soon!

**Pull request merged**
