### PR TITLE
feat: add dryRun option

### PR DESCRIPTION
**Pull request by bdenham**
Provides a `dryRun` option that is similar to the `—dry-run` command-line option found in the `jekyll-algolia` plugin.

### CODE REVIEW

**Comment by Haroenv** [comment]
This looks great, but in the mean time #135 has come, so that will cause some conflicts. Will you be able to rebase after I merge that PR?

Thanks for your work!

**Comment by bdenham** [comment]
Sure, no problem.

**Comment by Haroenv** [comment]
0.20.0 has this, thanks for your contribution!

**Comment by bdenham** [comment]
Hey @Haroenv! Thanks for getting that into the latest release! Much appreciated.

FYI, I'm currently on a team that will soon submit a PR (hopefully, next week) to add the HTML extractor feature (similar to what's in the `jekyll-algolia`) to this plugin. We really need that feature for our Gatsby sites. We use the jekyll plugin in our Jekyll sites to create separate records for each `p, li, td` and `code` tag in our pages using the `nodes_to_index` option. And we are really missing that feature in Gatsby-land!

So we're looking forward to contributing more to the plugin. Talk more later. Thanks again!

**Comment by Haroenv** [comment]
That sounds great! Just checking, isn't that something that makes more sense as a function you call manually in `transformer`?

**Comment by bdenham** [comment]
Hey @Haroenv! Yeah, it might make more sense doing it in the `transformer.` Perhaps that's what others who use this plugin are doing? I'll review that and have my teammate whose adding this feature look at that option instead. Thanks!

**Comment by Haroenv** [comment]
I don’t know of any other issues here explaining how to do it, but I’m pretty sure the topic has come up before and was sufficiently solved that way. If you’re happy with that, I’d love if you could add a small note on how to transform html to text easily to the readme

**Comment by naydav** [comment]
Hi @Haroenv,
I created corresponding tickethttps://github.com/algolia/gatsby-plugin-algolia/issues/137#issuecomment-848022940
Let's continue the discussion in the scope of it.
Thanks

**Pull request merged**
