### PR TITLE
fix: improve error message when index can not be found

### PR DESCRIPTION
**Pull request by joscha**
Currently, the error looks like this:

joscha_Joschas-MacBook-Pro____work_docs_eng-curriculum

I found this issue after myself and a bit of googling showed I am not the only one: https://stackoverflow.com/questions/61521867/why-did-i-fail-to-index-to-algolia/61523372#61523372

### CODE REVIEW

**Comment by develijahlee** [comment]
This was indeed a very cryptic error and I think the error should tell the user go to their Algolia dashboard and create an index with an updated name, as joscha said.

**Comment by joscha** [comment]
Happy to change this PR in any way that removes the cryptic error. You say Algolia creates the index automatically, but it guaranteed did not for me. I folllowed https://www.gatsbyjs.org/docs/adding-search-with-algolia/. If you hint me towards where to get the main index from that you are talking about I am happy to make changes to the pull request. Please keep in mind that you need a fresh Algolia account (without any indices) to reproduce it.

**Comment by samouss** [comment]
The Algolia API does [create the index](https://www.algolia.com/doc/api-client/getting-started/instantiate-client-index/#init-index) if you add any objects (or set a settings) to it, no doubt about that. I've tested locally with my application and an index that doesn't exist. I'm able to push objects to it.

The plugin though doesn't work when the index isn't created that's true. The function I've linked above select on which index to operate. By default we use a `tempIndex` to avoid to update the "main" index (i.e. `index` in the code above) used by the application. If the index already exists we use the temp one but if it doesn't we don't return an instance of the index. The fix is to return `index` in case it doesn't exist yet. That way it will be created on we push objects to it.

**Comment by Haroenv** [comment]
Thanks for this PR, but it's indeed solved by Samuel's PR as well

**Pull request closed without merging**
